# app.yaml
runtime: java17
instance_class: F2

env_variables:
  JAVA_USER_OPTS: "-Xmx1g"

handlers:
  # Serve all static files from the default static directory
  - url: /(.*\.(gif|png|jpg|ico|js|css|html|txt))$
    static_files: static/\1
    upload: static/(.*\.(gif|png|jpg|ico|js|css|html|txt))$

  # Route all other paths to your Java application
  - url: /.*
    script: auto
    secure: always

# Basic scaling configuration
basic_scaling:
  max_instances: 5
  idle_timeout: 10m

# Or use automatic scaling (choose one)
# automatic_scaling:
#   target_cpu_utilization: 0.65
#   min_instances: 1
#   max_instances: 10
#   min_pending_latency: 30ms
#   max_pending_latency: 100ms
